from __future__ import annotations

from pathlib import Path

import pandas as pd

from .paths import Q1Paths


COLUMN_LABELS = {
    "device_id": "设备编号",
    "date": "日期",
    "month": "月份",
    "daily_mean": "日均透水率",
    "daily_median": "日中位透水率",
    "daily_max": "日最大透水率",
    "daily_min": "日最小透水率",
    "daily_range": "日内极差",
    "daily_std": "日内标准差",
    "n_total_records": "当日记录数",
    "n_valid_records": "当日有效记录数",
    "daily_coverage_hours": "当日覆盖小时数",
    "daily_quality": "日数据质量",
    "gap_type": "缺失类型",
    "is_maintenance_day": "是否维护日",
    "maintenance_type_on_day": "当日维护类型",
    "days_since_last_maintenance": "距上次维护天数",
    "days_to_next_maintenance": "距下次维护天数",
    "days_from_observation_start": "距观测起点天数",
    "start_date": "起始日期",
    "end_date": "结束日期",
    "n_valid_days": "有效日数",
    "n_maintenance_gap_days": "维护结构缺失日数",
    "n_random_gap_days": "随机缺失日数",
    "alpha_median": "设备基础水平中位数",
    "alpha_mean": "设备基础水平均值",
    "daily_median_std": "日中位透水率标准差",
    "daily_median_min": "日中位透水率最小值",
    "daily_median_max": "日中位透水率最大值",
    "n_days_below_37": "低于37的有效日数",
    "section": "内容类别",
    "term": "项目",
    "value": "数值",
    "coef": "回归系数",
    "std_err": "标准误",
    "t_value": "t值",
    "p_value": "p值",
    "n_samples": "样本数",
    "r_squared": "R平方",
    "model_name": "模型名称",
    "n_maintenance_total": "维护总次数",
    "n_medium": "中维护次数",
    "n_major": "大维护次数",
    "maintenance_interval_median": "维护间隔中位数",
    "maintenance_interval_q25": "维护间隔下四分位数",
    "maintenance_interval_q75": "维护间隔上四分位数",
    "major_ratio": "大维护比例",
    "last_maintenance_date": "最近维护日期",
    "last_maintenance_type": "最近维护类型",
    "interval_sequence": "维护间隔序列",
    "type_sequence": "维护类型序列",
    "n_valid_cycles": "有效维护周期数",
    "cycle_length_median": "周期长度中位数",
    "cycle_decay_rate_mean": "周期衰减率均值",
    "cycle_decay_rate_median": "周期衰减率中位数",
    "cycle_decay_rate_q25": "周期衰减率下四分位数",
    "cycle_decay_rate_q75": "周期衰减率上四分位数",
    "cycle_drop_median": "周期下降量中位数",
    "maintenance_type": "维护类型",
    "n_jump_events": "即时跳升有效事件数",
    "jump_gain_median": "即时跳升中位数",
    "jump_gain_q25": "即时跳升下四分位数",
    "jump_gain_q75": "即时跳升上四分位数",
    "n_plateau_events": "平台提升有效事件数",
    "plateau_gain_median": "平台提升中位数",
    "plateau_gain_q25": "平台提升下四分位数",
    "plateau_gain_q75": "平台提升上四分位数",
    "post_7d_change_median": "维护后7日变化中位数",
    "post_7d_slope_median": "维护后7日斜率中位数",
    "h_max_initial_shrink": "最大可恢复水平初值_收缩",
    "post_recovery_trend_slope_per_day": "恢复高点日趋势斜率",
    "post_recovery_trend_reliable": "恢复高点趋势是否可靠",
    "medium_recovery_ratio_median": "中维护恢复比例中位数",
    "major_recovery_ratio_median": "大维护恢复比例中位数",
    "n_medium_rho_events": "中维护恢复比例有效事件数",
    "n_major_rho_events": "大维护恢复比例有效事件数",
    "rho_clipped_ratio_medium": "中维护恢复比例截断占比",
    "rho_clipped_ratio_major": "大维护恢复比例截断占比",
    "cycle_decay_rate_median": "周期衰减率中位数",
    "medium_plateau_gain_median": "中维护平台提升中位数",
    "major_plateau_gain_median": "大维护平台提升中位数",
}

COLUMN_LABELS.update(
    {
        "commission_date": "投用日期",
        "age_days_from_commission": "距投用天数",
        "age_days_at_start": "观测起点设备年龄天数",
        "age_days_at_end": "观测终点设备年龄天数",
        "current_state_level": "当前状态水平",
        "n_pure_decay_segments": "纯净衰减片段数",
        "pure_decay_rate_median": "纯净衰减率中位数",
        "pure_decay_rate_q25": "纯净衰减率下四分位数",
        "pure_decay_rate_q75": "纯净衰减率上四分位数",
        "early_pure_decay_rate_median": "早期纯净衰减率中位数",
        "late_pure_decay_rate_median": "晚期纯净衰减率中位数",
        "aging_acceleration_ratio": "老化加速比例",
        "monthly_decay_sensitive": "是否月度衰减敏感",
        "jump_gain_ratio": "即时跳升比例",
        "plateau_gain_ratio": "平台提升比例",
        "jump_gain_ratio_median": "即时跳升比例中位数",
        "plateau_gain_ratio_median": "平台提升比例中位数",
        "hold_ratio_7d": "维护后7日维持率",
        "hold_ratio_7d_median": "维护后7日维持率中位数",
        "upper_recovery_ratio": "恢复上限比例",
        "upper_recovery_ratio_median": "恢复上限比例中位数",
        "h_ref_q90": "健康参考水平Q90",
        "h_max_initial": "最大可恢复水平初值",
        "hmax_gap_to_current": "Hmax相对当前状态差值",
        "hmax_reliable": "Hmax是否可靠",
        "hmax_trend_slope_per_day": "Hmax日趋势斜率",
        "hmax_trend_used": "预测使用Hmax趋势",
        "medium_rho_median": "中维护恢复比例中位数",
        "major_rho_median": "大维护恢复比例中位数",
        "medium_rho_clip_ratio": "中维护rho截断占比",
        "major_rho_clip_ratio": "大维护rho截断占比",
        "medium_rho_reliable": "中维护rho是否可靠",
        "major_rho_reliable": "大维护rho是否可靠",
        "medium_recovery_ratio_used": "中维护预测使用恢复比例",
        "major_recovery_ratio_used": "大维护预测使用恢复比例",
        "rho_reliable_flag": "rho整体可靠标记",
        "medium_interval_median": "中维护典型间隔",
        "medium_interval_q25": "中维护间隔下四分位数",
        "medium_interval_q75": "中维护间隔上四分位数",
        "medium_min_interval": "中维护最小间隔",
        "medium_pre_decay_speed_median": "中维护前下降速度中位数",
        "medium_pre_decay_speed_q25": "中维护前下降速度下四分位数",
        "medium_pre_decay_speed_q75": "中维护前下降速度上四分位数",
        "major_interval_median": "大维护典型间隔",
        "major_interval_q25": "大维护间隔下四分位数",
        "major_interval_q75": "大维护间隔上四分位数",
        "medium_count_between_major_median": "两次大维护间中维护次数中位数",
        "major_rule_source": "大维护规则来源",
        "major_global_fallback_interval_days": "全局大维护兜底间隔天数",
        "major_global_fallback_event_count": "全局大维护兜底事件次数",
        "rule_reliable": "维护触发规则是否可靠",
        "last_major_maintenance_date": "最近大维护日期",
        "medium_since_last_major_at_end": "观测末距上次大维护后的中维护次数",
        "season_group": "季节组",
        "rho_median": "恢复比例中位数",
        "rho_clip_ratio": "rho截断占比",
        "kappa_gain": "固定增益季节修正因子",
        "kappa_rho": "恢复比例季节修正因子",
        "season_maintenance_effect_reliable": "季节维护效应是否可靠",
    }
)


def to_chinese_headers(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename(columns={column: COLUMN_LABELS.get(column, column) for column in df.columns})


def write_chinese_header_tables(paths: Q1Paths, tables: dict[str, pd.DataFrame]) -> None:
    paths.tables_cn_dir.mkdir(parents=True, exist_ok=True)
    for filename, df in tables.items():
        out_path: Path = paths.tables_cn_dir / filename
        to_chinese_headers(df).to_csv(out_path, index=False, encoding="utf-8-sig")
